### ISSUE TITLE
Memory issues `Error in `/opt/ee/python/3.8/bin/python': free(): invalid next size (fast): 0x00000001090bc250`

### ISSUE THREAD

**Issue by rllin** [meta-pytorch/torchrec#655] opened 2022-09-21 20:59 UTC
Inside the train_pipeline.py `progress` call

```
File ""/opt/ee/python/3.8/lib/python3.8/site-packages/torchrec/distributed/train_pipeline.py"", line 460 in _connect
```

I will sometimes get the following error
```
    "textPayload": "*** Error in `/opt/ee/python/3.8/bin/python': free(): invalid next size (fast): 0x00000001090bc250 ***",
```
Attached here is a csv of our logs.  the 2nd to last column is the error line

[downloaded-logs-20220921-135814.csv](https://github.com/pytorch/torchrec/files/9620339/downloaded-logs-20220921-135814.csv)

**Comment by colin2328** [comment] 2022-09-23 16:22
will look at the logs today, but in the meantime:
have you verfied the issue is actually with train_pipeline? (i,e are you able to put through some batches manually)
how deterministic is this error?

**Comment by colin2328** [comment] 2022-09-23 21:24
@rllin  I'm afraid nothing from the logs jumped out at me -> Is there a way you can share a smaller repro?

**Comment by colin2328** [comment] 2022-11-01 21:24
@rllin I'm going to close this issue as there's been no update on your end, feel free to repoen

**Closed as completed by colin2328** 2022-11-01 21:24 UTC
